/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableArray, NSString, NSTimer;

@interface AlarmController : NSObject
{
    NSMutableArray *_alarmList;
    NSTimer *_alarmTimer;
    NSMutableArray *_alarmsToFire;
    unsigned int _readingAlarms:1;
    NSTimer *_countDownTimer;
    double _countDownTime;
    NSString *_countDownTimerSoundIdentifier;
    struct __CFDate *_alarmWakeupDate;
    struct __CFDate *_countdownWakeupDate;
}

+ (id)sharedAlarmController;
- (void)_readAlarms;
- (void)_saveAlarms;
- (void)_alarmChanged:(id)fp8;
- (void)_resetCountDownTime;
- (id)init;
- (void)dealloc;
- (unsigned int)addAlarm:(id)fp8;
- (void)removeAlarmAtIndex:(unsigned int)fp8;
- (id)alarms;
- (void)_scheduleAlarms;
- (void)_alarmTimeReached:(id)fp8;
- (void)setCountDownTime:(double)fp8 withSoundIdentifier:(id)fp16;
- (void)_countDownTimerFired:(id)fp8;
- (void)_sleepTimerFired:(id)fp8;
- (double)countDownTime;
- (id)countDownTimerSoundIdentifier;
- (void)_wokeFromSleep;

@end

