/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSCalendarDate, NSString;

@interface Alarm : NSObject
{
    unsigned int _alarmHour;
    unsigned int _alarmMinute;
    int _alarmSetting;
    NSString *_alarmSoundIdentifier;
    NSString *_alarmTitle;
    NSCalendarDate *_snoozeUntilDate;
    unsigned int _isActive:1;
    unsigned int _repeats:1;
    unsigned int _allowsSnooze:1;
    unsigned int _dontSendUpdate:1;
    unsigned int _dontStopSnoozing:1;
    unsigned int _reserved:27;
}

- (id)description;
- (void)_update;
- (id)init;
- (id)_initWithDictionary:(id)fp8;
- (id)_prefsDictionary;
- (void)dealloc;
- (BOOL)alarmTimesEqualTo:(id)fp8;
- (void)setAlarmHour:(unsigned int)fp8 minute:(unsigned int)fp12;
- (void)getAlarmHour:(unsigned int *)fp8 minute:(unsigned int *)fp12;
- (id)_fireDateAfterDate:(id)fp8;
- (void)setActive:(BOOL)fp8;
- (BOOL)isActive;
- (void)setRepeats:(BOOL)fp8;
- (BOOL)repeats;
- (void)setDaySetting:(int)fp8;
- (int)daySetting;
- (void)setAllowsSnooze:(BOOL)fp8;
- (BOOL)allowsSnooze;
- (BOOL)isSnoozing;
- (void)startSnoozingFromDate:(id)fp8;
- (void)stopSnoozing;
- (id)_snoozeUntilDate;
- (void)setAlarmSoundIdentifier:(id)fp8;
- (id)alarmSoundIdentifier;
- (void)setAlarmTitle:(id)fp8;
- (id)alarmTitle;
- (void)_activateAlertItem;
- (void)fireAlarm;

@end

