/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct CalAlarmEngine;

struct CalDatabase;

struct CalEventExpirationMonitor;

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSZone;

struct __CFDate;

struct __CFDateFormatter;

struct __CFDictionary;

struct __CFMachPort;

struct __CFSet;

struct __CFString;

struct __CFTimeZone;

struct __CTCall;

struct __CTSMSMessage;

struct __CTServerConnection;

struct __GSEvent;

struct __GSFont;

typedef struct {
    int _field1;
    char _field2;
    char _field3;
    char _field4;
    char _field5;
    double _field6;
} CDAnonymousStruct1;

typedef struct {
    unsigned char voicemailAvailable;
    int voicemailCount;
    long long voicemailID;
} CDAnonymousStruct2;

