/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (void)push:(id)fp8;
- (id)pop;
- (id)popObject:(id)fp8;
- (id)top;
@end

