/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIColor;

@interface RoundedBorderView : UIView
{
    UIColor *_color;
}

- (id)initWithFrame:(struct CGRect)fp8 color:(id)fp24;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;

@end

