/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDismissOnlyAlertItem.h"

@class UITextViewLegacy;

@interface SBActivationInfoAlertItem : SBDismissOnlyAlertItem
{
    UITextViewLegacy *_textView;
}

+ (id)activeItem;
- (id)init;
- (void)dealloc;
- (BOOL)willShowInAwayItems;
- (void)didPresentAlertSheet:(id)fp8;
- (void)_updateTextView;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)_simStatusChanged:(id)fp8;
- (void)willActivate;
- (void)didDeactivateForReason:(int)fp8;

@end

