/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary;

@interface SBAccessoryController : NSObject
{
    NSDictionary *_lingoToApplicationMap;
    NSMutableDictionary *_availableAccessories;
}

+ (id)sharedAccessoryController;
- (id)init;
- (void)dealloc;
- (void)reloadLingoToApplicationMap;
- (void)_enableAccessoryIfNeeded:(id)fp8 forLingo:(int)fp12;
- (void)_disableAccessoryIfNeeded:(id)fp8 forLingo:(int)fp12;
- (void)accessoryAvailabilityChanged:(int)fp8 availability:(int)fp12;

@end

