/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBStatusBarBatteryView;

@interface SBActivationView : UIView
{
    UIView *_backgroundView;
    SBStatusBarBatteryView *_batteryView;
    int _mode;
}

- (id)initWithFrame:(struct CGRect)fp8 mode:(int)fp24;
- (int)mode;
- (void)dealloc;

@end

