/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIModalViewDelegate-Protocol.h"

@class UIModalView;

@interface SBAlertItem : NSObject <UIModalViewDelegate>
{
    UIModalView *_alertSheet;
    BOOL _disallowUnlockAction;
    BOOL _orderOverSBAlert;
    BOOL _preventLockOver;
}

- (id)alertSheet;
- (void)dealloc;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)shouldShowInLockScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)undimsScreen;
- (BOOL)unlocksScreen;
- (BOOL)dismissOnLock;
- (BOOL)willShowInAwayItems;
- (void)cleanPreviousConfiguration;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)lockLabel;
- (float)lockLabelFontSize;
- (double)autoDismissInterval;
- (void)setDisallowsUnlockAction:(BOOL)fp8;
- (BOOL)disallowsUnlockAction;
- (void)performUnlockAction;
- (void)setOrderOverSBAlert:(BOOL)fp8;
- (BOOL)preventLockOver;
- (void)setPreventLockOver:(BOOL)fp8;
- (void)willActivate;
- (void)didActivate;
- (void)willRelockForButtonPress:(BOOL)fp8;
- (void)dismiss;
- (void)screenDidUndim;
- (void)screenWillUndim;
- (void)willDeactivateForReason:(int)fp8;
- (void)didDeactivateForReason:(int)fp8;
- (id)awayItem;

@end

