/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBAlert;

@interface SBAlertDisplay : UIView
{
    SBAlert *_alert;
    unsigned int _displaysAboveStatusBar:1;
    unsigned int _shouldAnimateIn:1;
}

- (void)setAlert:(id)fp8;
- (id)alert;
- (void)launchURL:(id)fp8;
- (void)willDismiss;
- (void)dismiss;
- (void)setHandlerAlreadyActive:(BOOL)fp8;
- (void)alertDisplayWillBecomeVisible;
- (void)alertDisplayBecameVisible;
- (BOOL)displaysAboveStatusBar;
- (void)setDisplaysAboveStatusBar:(BOOL)fp8;
- (BOOL)isReadyToBeRemovedFromView;
- (void)setShouldAnimateIn:(BOOL)fp8;
- (BOOL)shouldAnimateIn;

@end

