/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class NSMutableArray, NSMutableDictionary, SBAlertDisplay, UIView;

@interface SBAlertWindow : UIWindow
{
    UIView *_contentLayer;
    unsigned int _isAnimating:1;
    unsigned int _isInvalid:1;
    unsigned int _handlerActive:1;
    float _finalAlpha;
    SBAlertDisplay *_currentDisplay;
    NSMutableArray *_stackedAlertDisplays;
    NSMutableDictionary *_alertToDisplayMap;
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (id)initWithContentRect:(struct CGRect)fp8;
- (void)_backgroundFadedIn;
- (void)orderOut:(id)fp8;
- (void)dealloc;
- (BOOL)isOpaque;
- (id)stackedDisplayForAlert:(id)fp8;
- (void)_fireBearTrap;
- (void)_setBearTrap;
- (void)_cancelBearTrap;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)displayAlert:(id)fp8;
- (BOOL)deactivateAlert:(id)fp8;
- (int)displayCount;
- (void)dismissWindow:(id)fp8;
- (void)alertDisplayWillDismiss;
- (void)popInCurrentDisplay;
- (id)currentDisplay;
- (void)setHandlerAlreadyActive:(BOOL)fp8;
- (BOOL)handlerAlreadyActive;

@end

