/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView, UILabel;

@interface SBAlertImageView : UIView
{
    UIImageView *_imageView;
    UILabel *_labelView;
}

- (id)initWithFrame:(struct CGRect)fp8 errorString:(id)fp24;
- (void)layoutSubviews;

@end

