/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDisplay.h"

@class NSMutableDictionary, SBAlertDisplay, SBAlertWindow;

@interface SBAlert : SBDisplay
{
    SBAlertDisplay *_display;
    NSMutableDictionary *_dictionary;
    SBAlertWindow *_deferredAlertWindow;
}

+ (void)registerForAlerts;
+ (id)alertWindow;
+ (void)test;
- (void)dealloc;
- (id)display;
- (void)setDisplay:(id)fp8;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (BOOL)displaysAboveLock;
- (BOOL)undimsDisplay;
- (float)finalAlpha;
- (double)animateInDuration;
- (struct CGRect)alertWindowRect;
- (BOOL)activate;
- (void)tearDownAlertWindow:(id)fp8;
- (void)removeFromView;
- (BOOL)deactivate;
- (BOOL)animatesDismissal;
- (BOOL)allowsInCallStatusBar;
- (float)autoDimTime;
- (int)statusBarMode;
- (int)statusBarOrientation;
- (void)didAnimateLockKeypadIn;
- (void)didAnimateLockKeypadOut;
- (void)didFinishAnimatingIn;
- (void)didFinishAnimatingOut;

@end

