/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRingingAlertItem.h"

@class Alarm;

@interface SBAlarmAlertItem : SBRingingAlertItem
{
    Alarm *_alarm;
    BOOL _snoozeAlarm;
}

- (id)initWithAlarm:(id)fp8;
- (void)dealloc;
- (void)setAlarm:(id)fp8;
- (id)alarm;
- (BOOL)allowsSnooze;
- (void)startSnoozingAndDeactivate;
- (void)autoMute;
- (void)willDeactivateForReason:(int)fp8;
- (id)lockLabel;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)soundIdentifier;
- (id)avClientName;
- (id)avAudioCategory;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;

@end

