/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDisplay.h"

@class NSBundle, NSDictionary, NSMutableArray, NSMutableSet, NSNumber, NSString, UIRemoteApplication;

@interface SBApplication : SBDisplay
{
    NSString *_bundleIdentifier;
    NSString *_roleIdentifier;
    NSString *_path;
    NSBundle *_bundle;
    NSDictionary *_infoDictionary;
    NSString *_displayName;
    NSString *_demoRole;
    NSNumber *_dataFlags;
    NSMutableSet *_statusBarItemSet;
    NSMutableArray *_tags;
    UIRemoteApplication *_remoteApplication;
    struct __CFSet *_launchAlerts;
    NSString *_seatbeltProfilePath;
    NSDictionary *_seatbeltEnvVars;
    NSString *_signerIdentity;
    int _signatureState;
    unsigned int _eventPort;
    unsigned int _doingBackgroundNetworking;
    unsigned int _failedLaunchCount;
    unsigned int _memoryWarningCount;
    unsigned int _enabled:1;
    unsigned int _useDemoRole:1;
    unsigned int _relauchesOnAbnormalExit:1;
    unsigned int _isDefaultRole:1;
    unsigned int _isSystemApplication:1;
}

+ (void)flushSnapshotsForIdentifier:(id)fp8;
+ (void)flushLaunchAlertsOfType:(int)fp8;
- (id)initWithBundleIdentifier:(id)fp8 roleIdentifier:(id)fp12 path:(id)fp16 bundle:(id)fp20 infoDictionary:(id)fp24 isSystemApplication:(BOOL)fp28;
- (void)_startWatchdogTimerWithTimeInterval:(double)fp8 selector:(SEL)fp16;
- (void)_startLaunchWatchdogTimer;
- (void)_startResumeWatchdogTimer;
- (void)_startDeactivationWatchdogTimer;
- (void)_startTerminationWatchdogTimer;
- (void)_cancelWatchdogTimer;
- (void)_scheduleWatchdogAssertionWithTimeout:(double *)fp8 token:(unsigned int)fp12;
- (unsigned int)addWatchdogAssertionWithTimeout:(double *)fp8;
- (void)renewWatchdogAssertionWithToken:(unsigned int)fp8 timeout:(double *)fp12;
- (void)removeWatchdogAssertionWithToken:(unsigned int)fp8;
- (void)_cancelWatchdogAssertExpiryTimer;
- (void)_watchdogAssertExpired:(id)fp8;
- (BOOL)shouldWatchdog;
- (BOOL)isBeingDebugged;
- (float)autoDimTime;
- (float)autoLockTime;
- (void)dealloc;
- (id)bundle;
- (id)infoDictionary;
- (id)bundleIdentifier;
- (void)setRoleIdentifier:(id)fp8;
- (id)roleIdentifier;
- (void)setIsDefaultRole:(BOOL)fp8;
- (BOOL)isDefaultRole;
- (id)path;
- (BOOL)enabled;
- (void)setEnabled:(BOOL)fp8;
- (id)demoRole;
- (void)setDemoRole:(id)fp8;
- (void)setUseDemoRole:(BOOL)fp8;
- (void)setTags:(id)fp8;
- (id)tags;
- (void)_addInternalDebugVariablesToEnvironment;
- (unsigned int)dataUsage;
- (void)_setDataUsage:(unsigned int)fp8;
- (void)setUsesBackgroundNetwork:(BOOL)fp8;
- (void)setUsesEdgeNetwork:(BOOL)fp8;
- (void)setUsesWiFiNetwork:(BOOL)fp8;
- (void)_resetDataUsage;
- (id)_additionalDisplayQualification;
- (id)displayIdentifier;
- (id)displayIdentifierWithURLScheme:(BOOL)fp8;
- (id)pathForIcon;
- (BOOL)isSystemApplication;
- (BOOL)shouldLaunchPNGless;
- (id)pathForDefaultImage:(char *)fp8;
- (id)displayName;
- (void)setDisplayName:(id)fp8;
- (void)_sendCurrentDeviceOrientation;
- (BOOL)activate;
- (BOOL)sendActivationEvent:(int)fp8;
- (BOOL)deactivate;
- (void)watchdogForDeactivate;
- (void)watchdogForResume;
- (void)watchdogForLaunch;
- (void)watchdogForTermination;
- (void)deactivated;
- (BOOL)kill;
- (void)_relaunchNow;
- (void)_relaunchAfterAbnormalExit:(BOOL)fp8;
- (void)removeStatusBarItems;
- (int)defaultStatusBarMode;
- (int)defaultStatusBarOrientation;
- (void)_resetEventPort;
- (void)exitedCommon;
- (void)exitedAbnormally;
- (void)exitedNormally;
- (unsigned int)priority;
- (int)pid;
- (void)setPid:(int)fp8;
- (unsigned int)eventPort;
- (id)launchdJobLabel;
- (void)setLaunchdJobLabel:(id)fp8;
- (id)seatbeltProfilePath;
- (void)setSeatbeltProfilePath:(id)fp8;
- (id)seatbeltEnvironmentVariables;
- (void)setSeatbeltEnvironmentVariables:(id)fp8;
- (id)signerIdentity;
- (void)setSignerIdentity:(id)fp8;
- (int)applicationSignatureState;
- (void)setApplicationSignatureState:(int)fp8;
- (void)markApplicationIdentityAsTrusted;
- (int)failedLaunchCount;
- (void)removeAppPrefs;
- (void)launchFailed;
- (void)launchSucceeded;
- (unsigned int)memoryWarningCount;
- (void)setMemoryWarningCount:(unsigned int)fp8;
- (void)setRelaunchesAfterAbnormalExit:(BOOL)fp8;
- (BOOL)relaunchesAfterAbnormalExit;
- (void)noteAddedStatusBarItem:(id)fp8;
- (void)noteRemovedStatusBarItem:(id)fp8;
- (id)remoteApplication;
- (BOOL)showLaunchAlertForType:(int)fp8;
- (void)resetLaunchAlertForType:(int)fp8;

@end

