/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@interface SBAppWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (id)initWithContentRect:(struct CGRect)fp8;
- (void)dealloc;
- (void)sendGSEvent:(struct __GSEvent *)fp8;
- (BOOL)shouldRespondToStatusBarHeightChange;

@end

