/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, NSTimer, TPLCDView, UIImage;

@interface SBAwayInCallController : NSObject
{
    TPLCDView *_lcdView;
    BOOL _showsInCallInfo;
    NSTimer *_durationTimer;
    struct __CTCall *_displayedCall;
    NSString *_localizedLabel;
    UIImage *_callerImage;
    BOOL _isFullScreen;
}

- (id)initWithLCDView:(id)fp8;
- (void)dealloc;
- (id)callerImage;
- (BOOL)callerImageIsFullScreen;
- (void)fetchCallInformation:(id *)fp8 name:(id *)fp12 label:(id *)fp16 image:(id *)fp20 isFullScreen:(char *)fp24;
- (void)updateDuration;
- (void)reload;
- (void)setShowsInCallInfo:(BOOL)fp8;

@end

