/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, SBAwayController;

@interface SBAwayModel : NSObject
{
    SBAwayController *_controller;
    NSMutableArray *_standardVMs;
    NSMutableArray *_calls;
    NSMutableArray *_SMSs;
    NSMutableArray *_otherAwayItems;
}

- (id)initWithController:(id)fp8;
- (void)dealloc;
- (void)markAwayTime;
- (void)addOtherAwayItem:(id)fp8;
- (void)addCall:(struct __CTCall *)fp8;
- (void)addSMSMessage:(struct __CTSMSMessage *)fp8;
- (void)populateWithMissedCalls:(id)fp8;
- (void)populateWithMissedSMS:(id)fp8;
- (void)populateWithMissedEnhancedVoiceMails:(id)fp8;
- (id)missedItems;
- (int)uncoalescedMissedItemCount;
- (void)setStandardVoiceMailCount:(int)fp8;

@end

