/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, NSTimer, SBAwayMediaControlsView, TPLCDTextView;

@interface SBAwayDateView : UIView
{
    NSTimer *_dateTimer;
    TPLCDTextView *_timeLabel;
    TPLCDTextView *_titleLabel;
    NSString *_title;
    SBAwayMediaControlsView *_controlsView;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12 fontName:(const char *)fp20;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12;
- (void)updateLabels;
- (void)setAlpha:(float)fp8;
- (void)updateClockFormat;
- (void)updateClock;
- (void)setTitle:(id)fp8;
- (void)removeFromSuperview;
- (void)movedToSuperview:(id)fp8;
- (id)controlsView;
- (void)setIsShowingControls:(BOOL)fp8;
- (BOOL)isShowingControls;

@end

