/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSString;

@interface SBAwayItem : NSObject
{
    NSString *_title;
    NSString *_secondTitle;
    int _uid;
    int _type;
    NSDate *_date;
    int _count;
}

- (id)initWithTitle:(id)fp8 uid:(int)fp12 type:(int)fp16 date:(id)fp20 count:(int)fp24;
- (id)initWithTitle:(id)fp8 uid:(int)fp12 type:(int)fp16 date:(id)fp20;
- (void)dealloc;
- (id)title;
- (void)setSecondTitle:(id)fp8;
- (id)secondTitle;
- (int)uid;
- (int)type;
- (id)description;
- (id)date;
- (int)compare:(id)fp8;
- (int)count;

@end

