/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class SBBatteryChargingView;

@interface SBAwayChargingView : UIView
{
    SBBatteryChargingView *_chargingView;
    SBBatteryChargingView *_headsetChargingView;
    unsigned int _animatingBatteries:1;
    unsigned int _updateAfterAnimation:1;
    unsigned int _showingDeviceBattery:1;
    unsigned int _showingHeadsetBattery:1;
}

+ (struct CGSize)defaultSize;
+ (BOOL)shouldShowDeviceBattery;
+ (BOOL)shouldShowHeadsetBattery;
- (id)initWithFrame:(struct CGRect)fp8 awayView:(id)fp24;
- (void)dealloc;
- (void)updateInterface:(BOOL)fp8;
- (id)chargingView;
- (void)addChargingView;
- (void)hideChargingView;
- (id)headsetChargingView;
- (void)addHeadsetChargingView;
- (void)hideHeadsetChargingView;
- (struct CGPoint)_dualBatteryPositionForBattery:(id)fp8;
- (struct CGPoint)_singleBatteryPositionForBattery:(id)fp8;
- (void)_switchFromBattery:(id)fp8 toView:(id)fp12 animate:(BOOL)fp16;
- (void)_slideBattery:(id)fp8 toShowBattery:(id)fp12 animate:(BOOL)fp16;
- (void)_slideBattery:(id)fp8 toHideBattery:(id)fp12 animate:(BOOL)fp16;
- (void)_finishedFadeForSwitch:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;
- (void)_finishedSlideForSlideToReveal:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;
- (void)_finishedHideForHideToSlide:(id)fp8 finished:(BOOL)fp12 context:(id)fp16;
- (void)_batteryAnimationFinished:(id)fp8;
- (void)_test:(id)fp8;

@end

