/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIPushButton, UIScrubberControl;

@interface SBAwayMediaControlsView : UIView
{
    unsigned int _seeked:1;
    UIPushButton *_prevButton;
    UIPushButton *_nextButton;
    UIPushButton *_playPauseButton;
    UIScrubberControl *_slider;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)_createButtonWithImage:(id)fp8 action:(SEL)fp12 tag:(int)fp16;
- (void)layoutSubviews;
- (void)_updateInformation;
- (void)setAlpha:(float)fp8;
- (void)_clearSeekedFlag:(id)fp8;
- (void)_controlButtonAction:(id)fp8;
- (void)_volumeChange:(id)fp8;
- (void)viewHandleTouchPause:(id)fp8 isDown:(BOOL)fp12;
- (double)viewTouchPauseThreshold:(id)fp8;
- (void)_registerForNowPlayingNotifications;
- (void)_unregisterForNowPlayingNotifications;
- (void)_registerForVolumeNotifications;
- (void)_unregisterForVolumeNotifications;
- (void)_nowPlayingChanged:(id)fp8;
- (void)_systemVolumeChanged:(id)fp8;

@end

