/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class NSDate, NSDictionary, NSMutableArray, NSString, NSTimeZone, NSTimer, SBAlertItem, SBAwayItem, SBAwayModel, SBAwayView, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;
    SBAwayModel *_model;
    SBAwayView *_awayView;
    NSTimer *_dimTimer;
    NSDate *_lockDate;
    SBAwayItem *_clickedItem;
    unsigned int _isLocked:1;
    unsigned int _isDimmed:1;
    unsigned int _isDimming:1;
    unsigned int _orderedOutDimmed:1;
    unsigned int _frontDimmed:1;
    unsigned int _isBlocked:1;
    unsigned int _makingEmergencyCall:1;
    unsigned int _appRequestedPasscodeEntry:1;
    unsigned int _needToMakeEmergencyCall:1;
    unsigned int _isSyncing:1;
    unsigned int _relockAfterUnlock:1;
    unsigned int _wasLockedOrMakingEmergencyCallBeforeSync:1;
    unsigned int _wasDeviceLockedBeforeSync:1;
    unsigned int _willLockAfterDelay:1;
    unsigned int _showOverheatUI:1;
    NSDictionary *_nowPlayingInfo;
    double _sleepDelay;
    SBSlidingAlertDisplay *_deviceUnlockDisplay;
    double _deviceLockBlockTime;
    double _deviceLockGracePeriodEndTimeInterval;
    NSTimeZone *_deviceLockGraceTimeZone;
    BOOL _devicePasscodeLoaded;
    NSString *_devicePasscode;
    NSMutableArray *_pendingAlertItems;
    SBAlertItem *_currentAlertItem;
    int _notifyLockStateToken;
    BOOL _notifyLockStateCurrentState;
}

+ (id)sharedAwayController;
+ (void)registerForAlerts;
- (id)initWithUIController:(id)fp8;
- (id)awayModel;
- (void)applicationDidFinishLaunching:(id)fp8;
- (struct CGRect)alertWindowRect;
- (float)finalAlpha;
- (BOOL)undimsDisplay;
- (id)awayView;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (void)alertDisplayWillBecomeVisible;
- (void)dealloc;
- (void)_releaseAwayView;
- (void)handleClickedItem:(id)fp8;
- (double)animateInDuration;
- (void)reactivatePendingAlertItems;
- (void)playLockSound;
- (void)_sendLockStateChangedNotification;
- (BOOL)showOverheatUI;
- (void)setShowOverheatUI:(BOOL)fp8;
- (void)_pendAlertItem:(id)fp8;
- (void)lock;
- (id)pendingAlertItems;
- (void)_unlockWithSound:(BOOL)fp8;
- (void)unlockWithSound:(BOOL)fp8;
- (void)unlockWithSound:(BOOL)fp8 alertDisplay:(id)fp12;
- (void)_resetGracePeriod;
- (void)_timeChanged;
- (void)_setupDeviceLockGracePeriod;
- (void)loadPasscode;
- (id)devicePasscode;
- (BOOL)isPasswordProtected;
- (void)activationChanged:(id)fp8;
- (BOOL)isDeviceLocked;
- (void)setDeviceLocked:(BOOL)fp8;
- (void)applicationRequestedDeviceUnlock;
- (void)cancelApplicationRequestedDeviceLockEntry;
- (void)_clearBlockedState;
- (BOOL)isBlocked;
- (BOOL)isPermanentlyBlocked:(double *)fp8;
- (void)noteSyncStateChanged;
- (BOOL)isSyncing;
- (void)noteResetRestoreStateChanged;
- (BOOL)isLocked;
- (void)lockBarStartedTracking:(id)fp8;
- (void)lockBarStoppedTracking:(id)fp8;
- (void)resetAwayItems;
- (void)frontLockedAnimationFinished;
- (void)_frontForSuspendedLockAfterDelay;
- (void)frontForSuspendedLockAfterDelay:(float)fp8;
- (BOOL)willLockAfterDelay;
- (void)setWillLockAfterDelay:(BOOL)fp8;
- (BOOL)shouldAnimateOthersSuspension;
- (void)printLockLog;
- (void)frontLocked:(BOOL)fp8 animate:(BOOL)fp12 automatically:(BOOL)fp16;
- (void)attemptUnlock;
- (BOOL)isAttemptingUnlock;
- (void)_finishedUnlockAttemptWithStatus:(BOOL)fp8;
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 alertDisplay:(id)fp12;
- (void)sleep;
- (void)preventIdleSleep;
- (void)wake;
- (void)cancelDimTimer;
- (void)restartDimTimer:(float)fp8;
- (BOOL)isDimmed;
- (BOOL)moveAlertItemToAwayView:(id)fp8;
- (void)cleansePendingQueueOfAwayItems;
- (void)dimTimerFired;
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12;
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12 dimmed:(BOOL)fp16;
- (double)sleepDelay;
- (void)delaySleepByNumberOfSeconds:(float)fp8;
- (void)dimScreen:(BOOL)fp8;
- (void)_undimScreen;
- (void)undimScreen;
- (void)activate;
- (BOOL)deactivate;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (BOOL)allowsInCallStatusBar;
- (int)statusBarMode;
- (BOOL)animatesDismissal;
- (void)orderOut;
- (void)didFinishAnimatingOut;
- (void)animator:(id)fp8 stopAnimation:(id)fp12;
- (void)clickItem:(id)fp8;
- (void)updateNowPlayingInfo:(id)fp8;
- (void)handleRequestedAlbumArtBytes:(char *)fp8 length:(unsigned int)fp12;
- (void)updateClockFormat;
- (void)makeEmergencyCall;
- (void)_activateEmergencyCall;
- (void)emergencyCallWasDisplayed;
- (void)emergencyCallWasRemoved;
- (BOOL)isMakingEmergencyCall;
- (void)didAnimateLockKeypadIn;
- (void)didAnimateLockKeypadOut;
- (id)currentAlertItem;
- (void)pendOrDeactivateCurrentAlertItem;
- (BOOL)isCurrentAlertItemRinging;
- (BOOL)attemptSnoozeRingingAlertItem;
- (void)stopRingingAlertItem;
- (void)snoozeOrStopRingingAlertItem;
- (BOOL)activateAlertItem:(id)fp8;
- (BOOL)wantsToHandleAlert:(id)fp8;
- (void)deactivateAlertItem:(id)fp8;
- (void)updateInCallUI;
- (BOOL)isShowingMediaControls;
- (void)hideMediaControls;
- (BOOL)_disableShowingMediaControls;
- (BOOL)toggleMediaControls;
- (void)toggleShowsIMEIandICCID:(id)fp8;

@end

