/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIImage, UIImageView;

@interface SBBatteryChargingView : UIView
{
    int _type;
    UIImageView *_topBatteryView;
    UIImageView *_bottomBatteryView;
    UIImageView *_reflectionView;
    UIImage *_lastBatteryImage;
    int _lastBatteryIndex;
    unsigned int _showReflection:1;
}

+ (struct CGSize)defaultSizeForType:(int)fp8;
+ (float)batteryHeightForType:(int)fp8;
+ (int)redChargeIndexForType:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8 type:(int)fp24;
- (void)dealloc;
- (void)setShowsReflection:(BOOL)fp8;
- (int)_currentBatteryIndex;
- (id)_imageFormatString;
- (void)_batteryStatusChanged:(id)fp8;

@end

