/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBBluetoothController : NSObject
{
    NSMutableArray *_devices;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)firstBTDeviceToReportBatteryLevel;
- (BOOL)canReportBatteryLevel;
- (float)batteryLevel;
- (void)noteDevicesChanged;
- (void)startWatchingForDevices;
- (void)stopWatchingForDevices;
- (void)iapDeviceChanged:(id)fp8;
- (void)addDeviceNotification:(id)fp8;
- (void)removeDeviceNotification:(id)fp8;
- (void)connectionChanged:(id)fp8;
- (void)batteryChanged:(id)fp8;
- (void)unjackAudio;

@end

