/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

@class NSBundle, NSString;

@interface SBBookmarkIcon : SBIcon
{
    NSBundle *_bundle;
    NSString *_displayName;
}

- (id)initWithBookmarkBundle:(id)fp8;
- (void)dealloc;
- (BOOL)allowsCloseBox;
- (id)bundle;
- (id)icon;
- (id)displayName;
- (id)displayIdentifier;
- (id)tags;
- (void)launch;
- (void)completeUninstall;

@end

