/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconList.h"

@interface SBButtonBar : SBIconList
{
}

+ (struct CGSize)defaultSize;
- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)fp8;
- (int)maxIconRows;
- (float)topIconPadding;
- (float)verticalIconPadding;
- (float)leftMarginForIconRowArray:(id)fp8;
- (struct CGPoint)originForIconAtX:(int)fp8 Y:(int)fp12;
- (id)iconAtPoint:(struct CGPoint)fp8 X:(int *)fp16 Y:(int *)fp20 proposedOrder:(int *)fp24;
- (id)iconAtPoint:(struct CGPoint)fp8 X:(int *)fp16 Y:(int *)fp20;
- (BOOL)isDock;

@end

