/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCallFailureAlertItem : SBAlertItem
{
    int _causeCode;
    NSString *_address;
    struct __CTCall *_call;
}

- (id)initWithCauseCode:(long)fp8 call:(struct __CTCall *)fp12;
- (void)dealloc;
- (void)_callback;
- (id)lockLabel;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)performUnlockAction;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (BOOL)isCallFailureAlertItem;

@end

