/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCallAlertDisplay.h"

@class TPBottomButtonBar, TPCallWaitingButton, TPPushButton;

@interface SBCallWaitingAlertDisplay : SBCallAlertDisplay
{
    TPCallWaitingButton *_ignoreButton;
    TPCallWaitingButton *_answerButton;
    TPPushButton *_answerAndReleaseButton;
    TPBottomButtonBar *_animatingBottomBar;
    unsigned int _didRelease:1;
    unsigned int _didHeldRelease:1;
    unsigned int _setupForThree:1;
}

+ (id)createBottomBarForInstance:(id)fp8;
+ (id)_createBottomButtonBarForDisplay:(id)fp8;
- (id)initWithSize:(struct CGSize)fp8;
- (void)dealloc;
- (void)_callCountChanged:(id)fp8;
- (void)_callWaitingControlsFaded;
- (void)_answerButtonsSwapped;
- (void)_setPhoneFlipBackAttribute;
- (void)ignore;
- (void)dismiss;
- (id)additionalURLParameter;
- (void)answerCall:(struct __CTCall *)fp8;
- (void)answerAndRelease:(id)fp8;
- (void)setMiddleContentAlpha:(float)fp8;
- (void)lockBarUnlocked:(id)fp8;
- (void)_bottomBarSwitchHalfDone;
- (void)_bottomBarSwitchDone;
- (void)_addCallWaitingButtons:(BOOL)fp8;

@end

