/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@interface SBCalendarIconContentsView : UIView
{
    unsigned int _highlighted:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setHighlighted:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

