/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createTopBarForInstance:(id)fp8;
+ (id)createBottomBarForInstance:(id)fp8;
- (void)ignore:(id)fp8;
- (void)callBack:(id)fp8;
- (void)setAlert:(id)fp8;

@end

