/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBCalendarAlertItem : SBAlertItem
{
    double _date;
    NSString *_title;
    NSString *_location;
    int _eventId;
    BOOL _isAllDay;
}

+ (void)registerForAlerts;
+ (void)alarmsDidFire:(id)fp8;
+ (void)significantTimeChange;
- (id)initWithDate:(double)fp8 title:(id)fp16 location:(id)fp20 eventId:(int)fp24 isAllDay:(BOOL)fp28;
- (void)dealloc;
- (id)_dayString:(BOOL)fp8;
- (id)_timeString;
- (id)_dateString:(BOOL)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)lockLabel;
- (void)didPresentAlertSheet:(id)fp8;
- (void)revealEvent;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)performUnlockAction;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)willShowInAwayItems;
- (id)awayItem;

@end

