/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBCallAlert : SBAlert
{
    BOOL _causedSuspension;
}

+ (void)registerForAlerts;
- (id)initWithCall:(struct __CTCall *)fp8;
- (void)dealloc;
- (void)_handleCallEvent:(struct __CTCall *)fp8;
- (void)_handleCallerIDEvent:(struct __CTCall *)fp8;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (BOOL)displaysAboveLock;
- (double)animateInDuration;
- (BOOL)useUIAlertSheetWhenUnlocked;
- (BOOL)animatesDismissal;
- (BOOL)allowsInCallStatusBar;

@end

