/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallAlertDisplay : SBSlidingAlertDisplay
{
    BOOL _wasToldToStopRinging;
    BOOL _answered;
    BOOL _pendingRing;
}

+ (id)createBottomLockBarForDisplay:(id)fp8;
+ (id)createBottomBarForInstance:(id)fp8;
- (void)dealloc;
- (void)ringOrVibrate;
- (void)stopRingingOrVibrating;
- (BOOL)wasToldToStopRinging;
- (void)ringerChanged;
- (void)updateLCDWithName:(id)fp8 label:(id)fp12 breakPoint:(unsigned int)fp16;
- (void)updateImageFromPerson:(void *)fp8;
- (void)updateCallInformationFromAlert;
- (void)setAlert:(id)fp8;
- (void)checkForStatusChange;
- (void)_ringIfNecessary;
- (void)alertDisplayWillBecomeVisible;
- (void)alertDisplayBecameVisible;
- (void)finishedAnimatingIn;
- (id)additionalURLParameter;
- (void)answerCall:(struct __CTCall *)fp8;
- (void)answerAndRelease;
- (void)answer:(id)fp8;
- (void)lockBarUnlocked:(id)fp8;
- (void)dismiss;
- (void)ignoreAndRelease;
- (void)ignore;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;

@end

