/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBCalendarController : NSObject
{
    struct __CFDateFormatter *_dayFormatter;
    struct __CFDate *_lastScheduledWake;
    int _unreadInvitationCount;
    struct CalEventExpirationMonitor *_expirationMonitor;
    struct CalAlarmEngine *_alarmEngine;
    struct CalDatabase *_database;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)_finishInitialization;
- (void)_databaseChanged:(id)fp8;
- (void)_unreadInvitationsExpired:(id)fp8;
- (void)_setInvitationUnreadCount:(int)fp8;
- (int)unreadInvitationCount;
- (void)_alertForInvitations;
- (void)_alarmsDidSchedule:(id)fp8;
- (void)_adjustOnWake;
- (void)_didWakeFromSleep;
- (void)_alarmsDidFire:(id)fp8;
- (void)_checkForTimeZoneIfNecessary;
- (void)_significantTimeChange;
- (void)_newSIM:(id)fp8;
- (id)_stringForDay:(CDAnonymousStruct1)fp8 withLongFormatString:(id)fp24 useAbbreviatedFormats:(BOOL)fp28;
- (id)stringForDay:(CDAnonymousStruct1)fp8 withLongFormatString:(id)fp24;
- (id)abbreviatedStringForDay:(CDAnonymousStruct1)fp8 withLongFormatString:(id)fp24;
- (void)playAlertSound;

@end

