/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

@interface SBDestinationHole : SBIcon
{
}

+ (id)sharedInstance;
- (id)_automationID;
- (id)displayIdentifier;
- (id)topRimmedIcon;
- (id)icon;
- (void)setDisplayedIcon:(id)fp8;
- (id)highlightedIcon;

@end

