/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@interface SBDimmingWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (id)initWithContentRect:(struct CGRect)fp8;
- (id)initWithDimmingImage:(id)fp8;

@end

