/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableDictionary, NSMutableSet;

@interface SBDisplay : NSObject
{
    NSMutableDictionary *_activationValues;
    NSMutableDictionary *_deactivationValues;
    int _activationSettings;
    int _deactivationSettings;
    NSMutableSet *_suppressVolumeHudCategories;
    float _autoDimOverride;
    float _autoLockOverride;
    float _accelerometerSampleInterval;
    unsigned int _expectsFaceContact:1;
    unsigned int _disallowTouchPoints:1;
    unsigned int _accelerometerDeviceOrientationChangedEventsEnabled:1;
    unsigned int _accelerometerRawEventsEnabled:1;
    unsigned int _proximityEventsEnabled:1;
    unsigned int _showsProgress;
}

+ (id)migrateVersion1DefaultState:(id)fp8;
+ (void)loadDisplayStates;
+ (void)saveDisplayStates;
+ (void)setDefaultValue:(id)fp8 forKey:(const id)fp12 displayIdentifier:(id)fp16;
+ (id)defaultValueForKey:(const id)fp8 displayIdentifier:(id)fp12;
+ (void)resetDefaultValuesForDisplayIdentifier:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)displayIdentifier;
- (void)clearActivationSettings;
- (void)setActivationSetting:(int)fp8 flag:(BOOL)fp12;
- (void)setActivationSetting:(int)fp8 value:(id)fp12;
- (id)activationValue:(int)fp8;
- (BOOL)activationSetting:(int)fp8;
- (void)clearDeactivationSettings;
- (void)setDeactivationSetting:(int)fp8 flag:(BOOL)fp12;
- (BOOL)deactivationSetting:(int)fp8;
- (void)setDeactivationSetting:(int)fp8 value:(id)fp12;
- (id)deactivationValue:(int)fp8;
- (BOOL)activate;
- (BOOL)deactivate;
- (void)deactivated;
- (BOOL)kill;
- (void)exitedAbnormally;
- (void)exitedNormally;
- (BOOL)allowsEventOnlySuspension;
- (BOOL)allowsInCallStatusBar;
- (void)updateStatusBar:(float)fp8 fence:(int)fp12 animation:(int)fp16;
- (void)updateStatusBar:(float)fp8;
- (int)defaultStatusBarMode;
- (int)statusBarMode;
- (int)defaultStatusBarOrientation;
- (int)statusBarOrientation;
- (float)autoDimTime;
- (void)setAutoDimTime:(float)fp8;
- (float)autoLockTime;
- (void)setAutoLockTime:(float)fp8;
- (void)setExpectsFaceContact:(BOOL)fp8;
- (BOOL)expectsFaceContact;
- (void)setAccelerometerDeviceOrientationChangedEventsEnabled:(BOOL)fp8 sampleInterval:(float)fp12;
- (BOOL)accelerometerDeviceOrientationChangedEventsEnabled;
- (float)accelerometerSampleInterval;
- (void)setAccelerometerRawEventsEnabled:(BOOL)fp8;
- (BOOL)accelerometerRawEventsEnabled;
- (void)setProximityEventsEnabled:(BOOL)fp8;
- (BOOL)proximityEventsEnabled;
- (void)setShowsProgress:(BOOL)fp8;
- (BOOL)showsProgress;
- (void)setSystemVolumeHUDEnabled:(BOOL)fp8 forCategory:(id)fp12;
- (BOOL)showSystemVolumeHUDForCategory:(id)fp8;
- (void)setTouchPointsAllowed:(BOOL)fp8;
- (BOOL)touchPointsAllowed;
- (id)description;
- (id)activationSettingsDescription;
- (id)deactivationSettingsDescription;

@end

