/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageView.h"

@interface SBDownloadingProgressBar : UIImageView
{
    UIImageView *_clipView;
    UIImageView *_fillView;
    float _progress;
}

+ (float)defaultHeight;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)trackImage;
- (id)fillImage;
- (void)setProgress:(float)fp8;
- (float)progress;
- (void)updateFill;

@end

