/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

@class ISDownload, NSString, SBDownloadingProgressBar;

@interface SBDownloadingIcon : SBIcon
{
    NSString *_displayID;
    ISDownload *_download;
    SBDownloadingProgressBar *_progressView;
    float _progress;
    BOOL _installing;
}

+ (id)displayIdentifierForDownload:(id)fp8;
- (id)initWithDisplayIdentifier:(id)fp8;
- (id)initWithDownload:(id)fp8;
- (void)dealloc;
- (void)setDisplayIdentifier:(id)fp8;
- (void)resetIconImage;
- (id)icon;
- (void)setDisplayedIcon:(id)fp8;
- (void)updateDisplayName;
- (id)displayName;
- (id)displayIdentifier;
- (id)tags;
- (void)launch;
- (BOOL)allowsCloseBox;
- (void)completeUninstall;
- (void)download:(id)fp8 encounteredError:(id)fp12;
- (void)downloadStatusChanged:(id)fp8;
- (void)setDownload:(id)fp8;
- (id)download;
- (void)retry;
- (void)remove;
- (id)uninstallAlertTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertCancelTitle;
- (void)_showAlertForError:(id)fp8;

@end

