/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "ISNetworkMonitor-Protocol.h"

@class ISDownloadQueue, ISImageCache, NSMutableDictionary;

@interface SBDownloadController : NSObject <ISNetworkMonitor>
{
    ISDownloadQueue *_downloadQueue;
    ISImageCache *_imageCache;
    NSMutableDictionary *_artworkDict;
    unsigned int _networkActiveCount;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setupQueue;
- (id)iconImageForDownload:(id)fp8;
- (void)_fetchArtworkForDownload:(id)fp8;
- (void)downloadQueue:(id)fp8 changedWithRemovals:(id)fp12 disappearances:(id)fp16;
- (void)downloadQueueError:(id)fp8;
- (void)_installationComplete:(id)fp8;
- (void)downloadQueue:(id)fp8 downloadStateChanged:(id)fp12;
- (BOOL)checkQueue;
- (id)currentDownloads;
- (void)_setImage:(struct CGImage *)fp8 forURL:(id)fp12;
- (void)imageCache:(id)fp8 loadedImage:(struct CGImage *)fp12 forURL:(id)fp16 fetchTag:(int)fp20;
- (void)storeSetNetworkIsActive:(BOOL)fp8;

@end

