/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, SBButtonBar, SBEditIcon;

@interface SBIconModel : NSObject
{
    NSDictionary *_iconState;
    NSMutableArray *_iconLists;
    SBButtonBar *_buttonBar;
    SBEditIcon *_editIcon;
    NSMutableDictionary *_allAppIcons;
    NSMutableArray *_displayedIcons;
    NSMutableArray *_buttonBarIcons;
    NSMutableSet *_hiddenIconTags;
    NSMutableSet *_visibleIconTags;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)changeVisibilityOfIconsWithVisibleTags:(id)fp8 hiddenTags:(id)fp12;
- (BOOL)iconIsVisible:(id)fp8;
- (void)replaceDownloadingDisplayIdentifier:(id)fp8 withDisplayIdentifier:(id)fp12;
- (void)removeIconForDisplayIdentifier:(id)fp8;
- (void)_completedUninstall:(id)fp8;
- (id)downloadingIconForDownload:(id)fp8;
- (void)_addDownloadingApplications;
- (void)_addBookmarks;
- (id)downloadingIconForDisplayIdentifier:(id)fp8;
- (id)bookmarkIconForDisplayIdentifier:(id)fp8;
- (void)reloadIconForDisplayIdentifier:(id)fp8;
- (Class)iconClassForApplication:(id)fp8;
- (void)loadAllIcons;
- (id)editIcon;
- (id)buttonBarIcons;
- (id)iconForDisplayIdentifier:(id)fp8;
- (id)iconState;
- (void)noteIconStateChangedExternally;
- (id)buttonBar;
- (id)iconLists;
- (void)uninstallBookmarkIcon:(id)fp8;
- (id)iconListContainingIcon:(id)fp8;
- (id)addEmptyIconList;
- (void)removeEmptyIconList:(id)fp8;
- (void)compactIconLists;
- (id)firstAvailableIconListX:(int *)fp8 Y:(int *)fp12;
- (BOOL)iconPositionInPlatformState:(id)fp8 X:(int *)fp12 Y:(int *)fp16 inIconListNumber:(int *)fp20;
- (void)addNewIconToDesignatedLocation:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16;
- (BOOL)iconListsAreDirty;
- (void)_writeIconState;
- (void)saveIconState;
- (void)relayout;
- (void)uninstallApplicationIcon:(id)fp8;

@end

