/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class NSString;

@interface SBIconLabel : UIControl
{
    NSString *_label;
    unsigned int _drawMoreLegibly;
    unsigned int _inDock:1;
    unsigned int _ellipsesText:1;
    unsigned int _kerningAllowed:1;
    unsigned int _textMightOverlap:1;
}

+ (void)initialize;
+ (void)preheatStylizedStrings;
- (id)initWithSize:(struct CGSize)fp8 label:(id)fp16;
- (void)dealloc;
- (void)setInDock:(BOOL)fp8;
- (void)setEllipsesText:(BOOL)fp8;
- (void)setKerningAllowed:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

