/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBInvitationAlertItem : SBAlertItem
{
    NSString *_title;
    NSString *_organizer;
    double _startDate;
    double _endDate;
    int _eventId;
    BOOL _allDay;
    BOOL _floats;
    int _count;
    int _status;
}

+ (id)activeInvitationAlertItems;
+ (void)_addActiveItem:(id)fp8;
+ (void)_removeActiveItem:(id)fp8;
+ (void)registerForAlerts;
+ (void)_significantTimeChange;
+ (struct __CFDateFormatter *)_customFormatter;
- (id)init;
- (id)initWithCount:(int)fp8;
- (id)initWithTitle:(id)fp8 organizerName:(id)fp12 startDate:(double)fp16 endDate:(double)fp24 floats:(BOOL)fp32 allDay:(BOOL)fp36 eventId:(int)fp40 status:(int)fp44;
- (void)dealloc;
- (void)didDeactivateForReason:(int)fp8;
- (int)eventId;
- (int)count;
- (int)status;
- (id)_stringForTime:(CDAnonymousStruct1)fp8;
- (id)_stringForDateTime:(CDAnonymousStruct1)fp8 timeZone:(struct __CFTimeZone *)fp24;
- (id)_dateString;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)lockLabel;
- (void)didPresentAlertSheet:(id)fp8;
- (void)revealEvent;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)performUnlockAction;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)willShowInAwayItems;

@end

