/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBLaunchdUtilities : NSObject
{
}

+ (BOOL)createJobWithLabel:(id)fp8 path:(id)fp12 arguments:(id)fp16 environment:(id)fp20 standardOutputPath:(id)fp24 standardErrorPath:(id)fp28 waitForDebugger:(BOOL)fp32 seatbeltProfilePath:(id)fp36 machServices:(id)fp40;
+ (void)deleteJobWithLabel:(id)fp8;
+ (BOOL)stopJobWithLabel:(id)fp8;
+ (BOOL)startJobWithLabel:(id)fp8;
+ (int)pidForLabel:(id)fp8;
+ (int)lastExitStatusForLabel:(id)fp8;
+ (id)allJobLabels;

@end

