/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBLowPowerAlertItem : SBAlertItem
{
    unsigned int _talkMinutesLeft;
    unsigned int _talkLevel;
}

+ (id)systemVersionDescription;
+ (void)saveLowBatteryLogWithCapacity:(int)fp8;
+ (void)savePowerDiagnosisLogWithCurrentCapacity:(int)fp8 startCapacity:(int)fp12;
+ (unsigned int)_thresholdForLevel:(unsigned int)fp8;
+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)fp8;
+ (void)setBatteryLevel:(unsigned int)fp8;
- (id)initWithTalkTimeLeft:(unsigned int)fp8 level:(unsigned int)fp12;
- (void)willPresentAlertSheet:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (BOOL)shouldShowInLockScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)undimsScreen;

@end

