/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPhoneAlertItem.h"

@interface SBNetworkReselectionAlertItem : SBPhoneAlertItem
{
}

+ (id)currentInstance;
+ (BOOL)hasCurrentInstance;
- (id)init;
- (void)_showPrefs;
- (id)lockLabel;
- (void)performUnlockAction;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)willDeactivateForReason:(int)fp8;

@end

