/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIImage;

@interface SBNowPlayingReflectionView : UIView
{
    UIImage *_image;
}

- (void)dealloc;
- (void)setImage:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

