/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIModalView.h"

@interface SBNowPlayingAlertSheet : UIModalView
{
    unsigned int _layoutAsLocked:1;
}

- (void)_positionControlButton:(int)fp8 withFloor:(float)fp12;
- (void)layout;
- (void)setLayoutAsLocked:(BOOL)fp8;

@end

