/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPushButton.h"

@interface SBNowPlayingAlertItemPushButton : UIPushButton
{
    float _yOffset;
    float _xOffset;
}

- (id)initWithImage:(id)fp8;
- (void)setYOffset:(float)fp8;
- (void)setXOffset:(float)fp8;
- (struct CGRect)hitRect;
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;

@end

