/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

#import "UITextFieldDelegate-Protocol.h"

@interface SBPasscodeAlertItem : SBAlertItem <UITextFieldDelegate>
{
    int _mode;
    BOOL _alphanumeric;
}

- (id)initWithPasscodeMode:(int)fp8 isAlphanumeric:(BOOL)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)returnKeyPressed:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (BOOL)shouldShowInLockScreen;
- (void)dismiss;
- (void)_setErrorString:(id)fp8;

@end

