/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, SBPasscodeAlertItem;

@interface SBPasscodeController : NSObject
{
    SBPasscodeAlertItem *_alertItem;
    int _mode;
    NSString *_password;
    NSString *_originalPassword;
    BOOL _alphanumeric;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)forceUserToChangePasscode;
- (void)_passwordEntered:(id)fp8;

@end

