/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SBPlatformController : NSObject
{
    NSString *_currentConfigurationName;
    NSMutableDictionary *_currentConfiguration;
    NSMutableDictionary *_currentCapabilities;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)systemBuildVersion;
- (id)infoForCapability:(id)fp8;
- (void)setInfo:(id)fp8 forCapability:(id)fp12;
- (void)addCapabilities:(id)fp8 removeCapabilities:(id)fp12;
- (BOOL)hasCapability:(id)fp8;
- (id)platformName;
- (id)iconState;
- (BOOL)matchesPlatforms:(id)fp8;
- (id)localizedPlatformName;
- (BOOL)isInternalInstall;

@end

