/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class UIView, UIWindow;

@interface SBScreenFlash : NSObject
{
    UIWindow *_flashWindow;
    UIView *_flashView;
    BOOL _windowVisible;
}

+ (id)sharedSBScreenFlash;
- (void)_createUI;
- (void)_tearDown;
- (void)_orderWindowOut:(id)fp8;
- (void)_orderWindowFront:(id)fp8;
- (void)stopFlash;
- (void)flash;
- (void)animationDidStop:(id)fp8 finished:(id)fp12;

@end

