/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitAlert.h"

@interface SBSIMToolkitAlert (PhoneAlert)
- (struct __CFString *)callPriority;
- (struct __CFString *)displayTextPriority;
- (BOOL)shouldRedial;
- (id)phoneNumber;
- (id)inCallText;
@end

