/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBSIMLockEntryAlert : SBAlert
{
    int _status;
}

- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (int)status;
- (BOOL)deactivate;

@end

