/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertInputView.h"

@interface SBSIMToolkitGetInputDisplay : SBAlertInputView
{
}

- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (void)alertDisplayWillBecomeVisible;
- (void)displayDidTimeout;
- (void)sbAlertInputViewSendClicked:(id)fp8;
- (void)sbAlertInputViewCancelClicked:(id)fp8;

@end

