/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSArray, UITable;

@interface SBSIMToolkitListDisplay : SBSlidingAlertDisplay
{
    UITable *_table;
    NSArray *_items;
}

+ (id)createTopBarForInstance:(id)fp8;
- (void)dealloc;
- (id)_simToolkitListItems;
- (void)_selectListItem:(unsigned long)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)fp8;
- (void)alertDisplayWillBecomeVisible;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (int)numberOfRowsInTable:(id)fp8;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;
- (void)tableSelectionDidChange:(id)fp8;

@end

