/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBSIMLockEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (id)_pinAttemptsRemainingLabel;
- (BOOL)alphanumericPIN;
- (void)setupUnlockAttemptState;
- (id)failureTitle;
- (id)failureLabel;
- (void)setupFailureState;
- (id)titleText;
- (id)label;
- (void)setupCurrentLockAttemptState;
- (void)alertDisplayWillBecomeVisible;
- (void)setupSuccess;
- (void)_unlock:(id)fp8;
- (void)unlock;
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;
- (void)passcodeFieldDidAcceptEntry:(id)fp8;

@end

