/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSIMToolkitGetInputDisplay.h"

@interface SBSIMToolkitOneShotGetInputDisplay : SBSIMToolkitGetInputDisplay
{
}

+ (id)createBottomBarForInstance:(id)fp8;
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;

@end

