/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIScroller;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay
{
    SBTextDisplayView *_contentView;
    UIScroller *_scroller;
}

+ (id)createTopBarForInstance:(id)fp8;
+ (id)createBottomBarForInstance:(id)fp8;
- (void)dealloc;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (void)adjustScrollerFrame;
- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)fp8;
- (void)displayDidTimeout;
- (id)alertText;
- (void)alertDisplayWillBecomeVisible;
- (void)accept:(id)fp8;
- (void)dismiss:(id)fp8;
- (void)dismiss;

@end

