/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUSSDAlert.h"

@interface SBSMSClass0Alert : SBUSSDAlert
{
}

+ (void)registerForAlerts;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (id)initWithString:(id)fp8;

@end

