/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString, NSTimer;

@interface SBStatusBarTimeView : SBStatusBarContentView
{
    NSTimer *_dateTimer;
    NSString *_time;
    struct CGRect _textRect;
}

- (id)init;
- (void)updateClockFormat;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)drawRect:(struct CGRect)fp8;
- (void)tile;
- (struct CGRect)textRect;

@end

