/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarSignalView : SBStatusBarContentView
{
    int _raw;
    int _bars;
    int _percentage;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)updateSignalStrength;
- (void)drawRect:(struct CGRect)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;

@end

