/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class SBStatusBarContentsView, SBStatusBarInCallView, SBStatusWindow, UIView;

@interface SBStatusBar : UIControl
{
    int _mode;
    int _orientation;
    SBStatusBarContentsView *_contentsView;
    SBStatusBarInCallView *_inCallView;
    SBStatusWindow *_statusWindow;
    UIView *_airplaneView;
    UIView *_glowView;
    UIView *_glassView;
    UIView *_dimmerView;
    unsigned int _animate:1;
    unsigned int _animating:1;
    unsigned int _isPressed:1;
    unsigned int _airplaneMode:1;
}

- (id)initWithMode:(int)fp8 orientation:(int)fp12;
- (void)setStatusWindow:(id)fp8;
- (id)statusWindow;
- (void)dealloc;
- (int)mode;
- (int)orientation;
- (id)contentsView;
- (id)airplaneView;
- (void)drawRect:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)start;
- (void)stop;
- (void)showDimmerOverlay:(BOOL)fp8;
- (void)setDimmerOverlayColor:(id)fp8;
- (void)startGlowAnimation;
- (void)stopGlowAnimation;
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12 ignoreAirPortPower:(BOOL)fp16;
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;
- (BOOL)isDimmed;
- (void)statusBarClicked;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;

@end

