/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@interface SBStatusBarBatteryView : SBStatusBarContentView
{
    int _batteryCapacity;
    BOOL _batteryCharging;
    BOOL _isOnAC;
}

- (void)updateBattery;
- (void)_batteryStatusChanged:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)setBatteryCapacity:(int)fp8 andCharging:(BOOL)fp12 isOnAC:(BOOL)fp16;
- (void)drawRect:(struct CGRect)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;

@end

