/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWindow.h"

@class UIView;

@interface SBStatusWindow : UIWindow
{
    int _orientation;
    UIView *_holderView;
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (BOOL)isOpaque;
- (id)initWithFrame:(struct CGRect)fp8;
- (int)orientation;
- (void)setOrientation:(int)fp8;
- (id)holderView;

@end

