/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString;

@interface SBStatusBarOperatorNameView : SBStatusBarContentView
{
    float _letterSpacing;
    NSString *_operatorName;
    BOOL _fullSize;
}

- (id)initWithOperatorName:(id)fp8;
- (void)dealloc;
- (id)operatorNameStyle;
- (void)drawRect:(struct CGRect)fp8;
- (float)calculateLetterSpacingForOperatorName:(id)fp8;
- (id)operatorName;
- (void)setOperatorName:(id)fp8 fullSize:(BOOL)fp12;

@end

