/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class NSString, NSTimer;

@interface SBStatusBarInCallView : SBStatusBarContentView
{
    double _inCallDuration;
    NSString *_durationPreamble;
    struct CGSize _durationPreambleSize;
    struct __GSFont *_font;
    NSTimer *_durationTimer;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)drawRect:(struct CGRect)fp8;

@end

