/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStatusBarContentView.h"

@class UIImage, UIImageView;

@interface SBStatusBarBluetoothView : SBStatusBarContentView
{
    UIImage *_icon;
    BOOL _animating;
    UIImageView *_activeView;
    UIImageView *_baseLayer;
    BOOL _isStarted;
}

+ (void)initialize;
- (id)icon;
- (id)init;
- (int)_effectiveMode;
- (void)_setupActiveView;
- (int)btStatus;
- (void)_btStatusChanged:(id)fp8;
- (void)_btDeviceConnected;
- (void)_btConnectionStatusChanged:(id)fp8;
- (void)_btDeviceDisconnected:(id)fp8;
- (void)animationDidStop:(id)fp8;
- (void)_start;
- (void)_btPowerPrefChanged:(id)fp8;
- (void)start;
- (void)stop;
- (void)dealloc;

@end

