/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSyncController : NSObject
{
    int _syncState;
    int _restoreState;
    int _resetState;
    int _sofwareUpdateState;
    struct __CFMachPort *_backupAgentCFPort;
    BOOL _showingResetUI;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)startObserving;
- (void)stopObserving;
- (BOOL)isSyncing;
- (int)syncState;
- (void)didEndSyncing;
- (void)suspendSyncing;
- (void)resumeSyncing;
- (void)cancelSyncing;
- (void)_notifyAppsSyncWillBegin;
- (void)didShowSyncPanel;
- (void)frontLockedWhenPossible;
- (void)beginSyncing;
- (void)iTunesSyncRequestedStart;
- (void)iTunesSyncHasCompleted:(int)fp8;
- (BOOL)isRestoring;
- (int)restoreState;
- (void)_notifyRestoreCanProceed;
- (void)_killApplications;
- (void)beginRestoring;
- (void)finishedTerminatingApplications;
- (void)cancelRestoring;
- (void)_rebootNow;
- (void)finishEndRestoring;
- (void)didEndRestoring:(int)fp8;
- (BOOL)isResetting;
- (int)resetState;
- (void)_delayedQuitApplications;
- (void)_delayedBeginReset;
- (void)beginResetting:(BOOL)fp8;
- (void)didEndResetting;
- (void)_resetStarted:(id)fp8;
- (void)_resetEnded:(id)fp8;
- (void)_invalidateBackupAgentCFPort;
- (void)_didEndRestoringWithRestoreFailed;
- (BOOL)_setupBackupAgentPort;
- (void)setSoftwareUpdateState:(int)fp8;
- (void)showPreSoftwareUpdateScreen;
- (BOOL)isSoftwareUpdating;
- (BOOL)isInUse;

@end

