/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBTelephonyManager : NSObject
{
    NSString *_operatorName;
    unsigned int _usingWifi:1;
    unsigned int _usingVPN:1;
    unsigned int _iTunesNeedsToRecheckActivation:1;
}

+ (id)sharedTelephonyManager;
- (id)init;
- (struct __CTServerConnection *)_serverConnection;
- (void)updatePhoneNumberPrefs;
- (void)updateTTYIndicator;
- (double)inCallDuration;
- (void)updateSpringBoard;
- (void)updateAirplaneMode;
- (void)updateCalls;
- (void)_updateState;
- (void)updateLocale;
- (void)updateNetworkLocale;
- (void)handleSIMReady;
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20;
- (id)displayForOutgoingCallURL:(id)fp8;
- (void)_mainThreadDaemonRestart:(struct __CFDictionary *)fp8;
- (void)_delayedAudioResume;
- (long long)getRowIDOfLastCallInsert;
- (id)allMissedCallsAfterRowID:(long long)fp8;
- (long long)getRowIDOfLastSMSInsert;
- (id)allUnreadSMSAfterRowID:(long long)fp8;
- (void)markMessageAsRead:(struct __CTSMSMessage *)fp8;
- (void)updateSMSBadges;
- (int)callCount;
- (BOOL)activeCallExists;
- (BOOL)heldCallExists;
- (BOOL)incomingCallExists;
- (BOOL)outgoingCallExists;
- (BOOL)inCallUsingReceiver;
- (BOOL)callWouldUseReceiver:(BOOL)fp8;
- (BOOL)shouldHangUpOnLock;
- (BOOL)inCall;
- (void)disconnectIncomingCall;
- (void)answerIncomingCall;
- (void)answerIncomingCallEndingOthers;
- (void)swapCalls;
- (void)disconnectAllCalls;
- (void)disconnectCall;
- (void)disconnectCallAndActivateHeld;
- (void)unmute;
- (void)dumpBasebandState:(id)fp8;
- (BOOL)MALoggingEnabled;
- (void)powerOffRadio;
- (BOOL)isNetworkRegistrationEnabled;
- (void)setNetworkRegistrationEnabled:(BOOL)fp8;
- (int)dataConnectionType;
- (BOOL)EDGEIsOn;
- (BOOL)isUsingDataConnection;
- (BOOL)isUsingWiFiConnection;
- (void)setIsUsingWiFiConnection:(BOOL)fp8;
- (void)setIsUsingVPNConnection:(BOOL)fp8;
- (BOOL)isUsingVPNConnection;
- (void)copyICCID:(id *)fp8 IMEI:(id *)fp12;
- (void)configureForTTY:(BOOL)fp8;
- (BOOL)shouldPromptForTTY;
- (id)ttyTitle;
- (void)_resetCTMMode;
- (void)_headphoneChanged:(id)fp8;
- (void)_setRegistrationStatus:(int)fp8;
- (void)_updateRegistrationNow;
- (void)_cancelFakeService;
- (void)_startFakeServiceIfNecessary;
- (void)_stopFakeService;
- (id)_fetchOperatorName;
- (void)_reallySetOperatorName:(id)fp8;
- (void)setOperatorName:(id)fp8;
- (id)operatorName;
- (int)registrationStatus;
- (void)checkForRegistrationSoon;
- (void)kickStartSearching;
- (id)SIMStatus;
- (int)registrationCauseCode;
- (void)noteSIMUnlockAttempt;

@end

