/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface SBTextDisplayView : UIView
{
    NSString *_text;
    NSString *_style;
}

- (id)initWithWidth:(float)fp8 text:(id)fp12 style:(id)fp16;
- (void)dealloc;
- (void)_updateText;
- (void)setStyle:(id)fp8;
- (void)setText:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

