/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBTetherController : NSObject
{
    int _tetherState;
}

+ (id)sharedInstance;
- (BOOL)isTethered;
- (void)noteInterfaceOrientationChanged;
- (void)setDitheringEnabled:(int)fp8;
- (void)updatePreferencesIfNeeded;

@end

