/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPageControl.h"

@interface SBTouchPageIndicator : UIPageControl
{
    id _delegate;
}

- (void)setDelegate:(id)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;

@end

