/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createTopBarForInstance:(id)fp8;
+ (id)createBottomBarForInstance:(id)fp8;
- (id)initWithSize:(struct CGSize)fp8;
- (void)_makeCall;
- (void)_chooseVoiceMode:(id)fp8;
- (void)_chooseTTYMode:(id)fp8;
- (void)_ignore:(id)fp8;

@end

