/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBTVOutController : NSObject
{
    int _tvOutMode;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setIntialTVModeIfNeeded;
- (void)updateLayerKitSettings;
- (void)updateSettings;
- (int)tvOutMode;
- (void)setTvOutMode:(int)fp8;

@end

