/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class SBApplication, SBContentLayer, SBZoomView, UIView, UIWindow;

enum SBLaunchState {
	SBLaunchStateNormal = 0,
	SBLaunchStateAnimatingOpen = 1,
	SBLaunchStateApplicationRunning = 3,
	SBLaunchStateAnimatingClosed = 5
} _SBLaunchState;

@interface SBUIController : NSObject
{
    UIWindow *_window;
    UIView *_iconsView;
    UIView *_buttonBarContainerView;
    SBContentLayer *_contentLayer;
    SBZoomView *_zoomLayer;
    SBApplication *_launchedApp;
    int _launchState;
    BOOL _lastVolumeDownToControl;
    BOOL _shouldAutoLock;
    int _batteryCapacity;
    BOOL _isBatteryCharging;
    BOOL _isOnAC;
    BOOL _connectedToUnusableFirewire;
    BOOL _cancelingLaunch;
    int _batteryLoggingStartCapacity;
    unsigned char _headsetBatteryCapacity;
    BOOL _isHeadsetCharging;
    BOOL _isHeadsetDocked;
}

+ (int)displayedLevelForBatteryLevel:(int)fp8;
+ (int)displayedLevelForBatteryStatusBarLevel:(int)fp8;
+ (id)sharedInstance;
- (void)_indicateConnectedToPower;
- (void)dealloc;
- (id)init;
- (void)animateAppleDown:(BOOL)fp8;
- (BOOL)launchedAfterLanguageRestart;
- (void)clearLaunchedAfterLanguageRestart;
- (float)calculateStartupTime;
- (id)getVMstats;
- (void)logStartupData;
- (void)languageChanged;
- (void)finishLaunching;
- (void)systemControllerRouteChanged:(id)fp8;
- (void)lock:(BOOL)fp8;
- (void)lock;
- (int)launchState;
- (void)clearZoomLayer;
- (void)setState:(int)fp8;
- (id)contentView;
- (id)statusBarWindow;
- (id)window;
- (void)showZoomLayerForApp:(id)fp8;
- (void)stopAllAnimations;
- (void)hideIconListAndBar:(BOOL)fp8;
- (void)insertAndOrderIconListsForReordering:(BOOL)fp8;
- (void)restoreIconList:(BOOL)fp8 force:(BOOL)fp12;
- (void)stopRestoringIconList;
- (void)showButtonBar:(BOOL)fp8 animate:(BOOL)fp12 action:(SEL)fp16 delegate:(id)fp20;
- (void)quitTopApplication;
- (struct CGAffineTransform)_initialStatusBarTransformForScale:(float)fp8;
- (void)animateLaunchOfApplication:(id)fp8 afterDelay:(double)fp12 startingAtTime:(double)fp20 forDuration:(double)fp28 includingIconsAndButtonBar:(BOOL)fp36 initialZoomScale:(float)fp40 fadeInZoom:(BOOL)fp44;
- (void)cancelLaunchOfApplication:(id)fp8 duration:(double)fp12;
- (void)animateLaunchOfApplication:(id)fp8;
- (void)animateLaunchApplication:(id)fp8;
- (double)animateLaunchForReturnToLastApp:(id)fp8;
- (void)finishedFadingInButtonBar;
- (void)showZoomLayerAnimationDidStop:(id)fp8 finished:(id)fp12;
- (void)cancelLaunchAnimationDidStop:(id)fp8 finished:(id)fp12;
- (void)clickedMenuButton;
- (void)completeAlertDisplay;
- (void)wakeUp:(id)fp8;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;
- (int)batteryCapacity;
- (BOOL)isBatteryCharging;
- (BOOL)isOnAC;
- (void)ACPowerChanged;
- (void)setIsConnectedToUnusableFirewireCharger:(BOOL)fp8;
- (BOOL)isConnectedToUnusableFirewireCharger;
- (void)noteStatusBarHeightChanged:(float)fp8 duration:(double)fp12;
- (BOOL)isHeadsetDocked;
- (BOOL)isHeadsetBatteryCharging;
- (unsigned char)headsetBatteryCapacity;
- (void)handleAccessoryAvailabilityChange:(struct __GSEvent *)fp8 removal:(BOOL)fp12;
- (void)handleAccessoryEvent:(struct __GSEvent *)fp8;

@end

