/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDismissOnlyAlertItem.h"

@interface SBUnsupportedURLAlertItem : SBDismissOnlyAlertItem
{
}

+ (id)activeUnsupportedURLAlertItem;
- (void)dealloc;
- (void)willActivate;
- (void)willDeactivateForReason:(int)fp8;

@end

