/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableSet, NSTimer;

@interface SBVODController : NSObject
{
    NSMutableArray *_alarms;
    NSMutableSet *_alarmsToFire;
    NSMutableSet *_alarmsToFireWhenMovieEnds;
    NSTimer *_timer;
    NSTimer *_movieTimeoutTimer;
    unsigned int _reloadingForBoot:1;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)didWakeFromSleep;
- (void)reloadAlarms:(BOOL)fp8;
- (void)iTunesSyncRequestedStart;
- (void)iTunesSyncHasCompleted:(int)fp8;
- (void)alarmDidSanityCheck:(id)fp8;
- (void)_alarmFired:(id)fp8;
- (void)_presentAlarmAlerts:(id)fp8;
- (void)_presentAlarmsHavingFiredSinceDate:(id)fp8;
- (void)_scheduleTimer;
- (void)_writeTimeToDefaults;
- (BOOL)_alarmIsExpired:(id)fp8 hints:(id)fp12;
- (id)_expiredAlarmsPath;
- (void)_noteExpiredAlarms:(id)fp8;
- (void)_movieEndTimeout:(id)fp8;
- (void)_nowPlayingInfoChanged;
- (void)_sanityCheckExpiredAlarms:(id)fp8;
- (void)_significantTimeChanged:(id)fp8;

@end

