/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDismissOnlyAlertItem.h"

@interface SBVoiceMailAlertItem : SBDismissOnlyAlertItem
{
    BOOL _isForVisualVoicemail;
    unsigned int _recordUID;
}

+ (id)currentInstance;
+ (BOOL)hasCurrentInstance;
- (BOOL)isForVisualVoicemail;
- (void)setIsVisualVoicemail:(BOOL)fp8 recordUID:(unsigned int)fp12;
- (void)didDeactivateForReason:(int)fp8;
- (BOOL)willShowInAwayItems;
- (void)performUnlockAction;
- (id)lockLabel;

@end

