/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

#import "UIModalViewDelegate-Protocol.h"

@class SBVODAlarm;

@interface SBVODAlertItem : SBAlertItem <UIModalViewDelegate>
{
    SBVODAlarm *_alarm;
}

+ (id)activeAlertForAlarm:(id)fp8;
- (void)dealloc;
- (void)setAlarm:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (BOOL)unlocksScreen;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)screenWillUndim;
- (void)willActivate;
- (void)willDeactivateForReason:(int)fp8;
- (void)_updateText;

@end

