/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface SBVODAlarm : NSObject
{
    NSString *_title;
    NSString *_path;
    NSDictionary *_rentalInfo;
    unsigned int _loadingRentalInfo:1;
    unsigned int _sanityCheckingExpiration:1;
    unsigned int _watched:1;
}

+ (void)cancelPendingLoads;
+ (void)_rentalInfoThread;
- (id)initWithDictionary:(id)fp8;
- (void)dealloc;
- (int)compare:(id)fp8;
- (id)expirationDate;
- (BOOL)hasLoaded;
- (BOOL)isExpired;
- (BOOL)rentalHasBeenWatched;
- (BOOL)hasFireDateSinceDate:(id)fp8;
- (id)nextFireDate;
- (id)path;
- (void)sanityCheckExpiration;
- (id)title;
- (id)_dateWithStartDate:(id)fp8 duration:(id)fp12;
- (id)_rentalInfo;
- (void)_setRentalInfo:(id)fp8;

@end

