/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBWeatherApplicationIcon : SBApplicationIcon
{
}

- (id)initWithApplication:(id)fp8;
- (void)dealloc;
- (void)resetIcon;
- (BOOL)showFahrenheit;
- (id)icon;

@end

