/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSArray, NSString;

@interface SBWiFiTrustAlertItem : SBAlertItem
{
    NSString *_displayName;
    NSString *_networkName;
    NSArray *_certificateArray;
    BOOL _sentResponse;
}

- (id)alertSheet;
- (id)initWithCertificateArray:(id)fp8 networkName:(id)fp12;
- (void)dealloc;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)didDeactivateForReason:(int)fp8;
- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;

@end

