/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@interface SBWiFiIsEnterpriseAlert : SBAlertItem
{
    id _delegate;
}

- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)setDelegate:(id)fp8;
- (void)dismiss;

@end

