/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageView.h"

@interface SBZoomView : UIImageView
{
}

- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24 isInCall:(BOOL)fp28 preventSplit:(BOOL)fp32;

@end

