/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SpringBoard.h"

@interface SpringBoard (SBApplicationTesting)
- (BOOL)runTest:(id)fp8 options:(id)fp12;
- (void)_retryLaunchTestWithOptions:(id)fp8;
- (void)startLaunchTestNamed:(id)fp8 options:(id)fp12;
- (void)startResumeTestNamed:(id)fp8 options:(id)fp12;
- (void)endLaunchTest;
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;
@end

