/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet, NSString, UIWindow, VolumeControlView;

@interface VolumeControl : NSObject
{
    UIWindow *_volumeWindow;
    VolumeControlView *_volumeView;
    BOOL _windowVisible;
    BOOL _debounce;
    int _mode;
    NSMutableSet *_alwaysHiddenCategories;
    NSString *_lastDisplayedCategory;
    NSString *_lastEventCategory;
}

+ (id)sharedVolumeControl;
- (id)init;
- (void)dealloc;
- (void)reorientHUDIfNeeded:(BOOL)fp8;
- (void)_createUI;
- (void)_tearDown;
- (void)_orderWindowOut:(id)fp8;
- (void)addAlwaysHiddenCategory:(id)fp8;
- (void)removeAlwaysHiddenCategory:(id)fp8;
- (BOOL)_HUDIsDisplayableForCategory:(id)fp8;
- (float)_windowFadeDelay;
- (void)_orderWindowFront:(id)fp8 forCategory:(id)fp12;
- (BOOL)_allowVolumeChangeForCategory:(id)fp8;
- (void)_changeVolumeBy:(float)fp8;
- (float)_calcButtonRepeatDelay;
- (void)increaseVolume;
- (void)decreaseVolume;
- (void)hideHUD;
- (void)showHUD;
- (id)lastDisplayedCategory;
- (void)setHUDMode:(int)fp8;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;
- (void)cancelVolumeEvent;
- (void)animationDidStop:(id)fp8 finished:(id)fp12;
- (void)_registerForAVSystemControllerNotifications;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)_serverConnectionDied:(id)fp8;
- (int)_volumeModeForCategory:(id)fp8;
- (void)_systemVolumeChanged:(id)fp8;

@end

