/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UITextLabel;

@interface VolumeControlView : UIView
{
    float _volume;
    int _mode;
    BOOL _headphonesPresent;
    UITextLabel *_label1;
    UITextLabel *_label2;
    NSString *_line1;
    NSString *_line2;
}

+ (void)loadImages;
+ (struct CGSize)controlSize;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)_checkHeadphonesPresent;
- (void)setMode:(int)fp8;
- (void)setVolume:(float)fp8 mode:(int)fp12;
- (float)volume;
- (void)_updateLabelStrings;
- (void)dealloc;
- (BOOL)_showLabel;
- (void)_drawLine1;
- (void)_drawLine2;
- (void)drawRect:(struct CGRect)fp8;

@end

