/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

typedef enum {
    kUIBezierPathTopLeftCorner = 1,
    kUIBezierPathTopRightCorner = 1 << 1,
    kUIBezierPathBottomLeftCorner = 1 << 2,
    kUIBezierPathBottomRightCorner = 1 << 3,
    kUIBezierPathAllCorners = (kUIBezierPathTopLeftCorner | kUIBezierPathTopRightCorner | kUIBezierPathBottomLeftCorner | kUIBezierPathBottomRightCorner)
} UIBezierPathCornerOptions;

@interface UIBezierPath : NSObject {}

+ (id)bezierPath;	
+ (id)bezierPathKnockingOutBottomOfRect:(CGRect)rect withCornerRadius:(float)radius;	
+ (id)bezierPathKnockingOutTopOfRect:(CGRect)rect withCornerRadius:(float)radius;	
+ (id)roundedRectBezierPath:(CGRect)rect withRoundedCorners:(UIBezierPathCornerOptions)cornerOptions visibleEdges:(int)fp28 cornerRadius:(float)radius;	
+ (id)roundedRectBezierPath:(CGRect)rect withRoundedCorners:(UIBezierPathCornerOptions)cornerOptions withCornerRadii:(id)fp28; // NSArray of NSNumbers?
+ (id)roundedRectBezierPath:(CGRect)rect withRoundedCorners:(UIBezierPathCornerOptions)cornerOptions withCornerRadius:(float)radius;	
+ (id)roundedRectBezierPath:(CGRect)rect withRoundedEdges:(UIBezierPathCornerOptions)cornerOptions;	
- (CGPathRef)_pathRef;	
- (void)appendBezierPath:(UIBezierPath *)path;	
- (void)appendBezierPathWithArcWithCenter:(CGPoint)center radius:(float)radius startAngle:(float)startAngle endAngle:(float)endAngle clockwise:(BOOL)clockwise;	
- (void)appendBezierPathWithOvalInRect:(CGRect)rect;	
- (void)appendBezierPathWithOvalInRect:(CGRect)rect transform:(CGAffineTransform)transform;	
- (void)appendBezierPathWithRect:(CGRect)rect;	
- (void)clip;	
- (void)closePath;	
- (void)dealloc;	
- (void)fill;	
- (id)init;	
- (void)lineToPoint:(CGPoint)point;	
- (void)moveToPoint:(CGPoint)point;	
- (void)setLineWidth:(float)point;	
- (void)stroke;	

@end
