/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class PSListController;

@interface PSBundleController : NSObject
{
    PSListController *_parent;
}

- (void)load;
- (void)unload;
- (id)specifiersWithSpecifier:(id)fp8;
- (id)initWithParentListController:(id)fp8;

@end

