/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSSpecifier.h>

@class NSString;

@interface PSConfirmationSpecifier : PSSpecifier
{
    NSString *_title;
    NSString *_okButton;
    NSString *_cancelButton;
}

+ (id)preferenceSpecifierNamed:(id)fp8 target:(id)fp12 set:(SEL)fp16 get:(SEL)fp20 detail:(Class)fp24 cell:(int)fp28 edit:(Class)fp32;
- (void)setupWithDictionary:(id)fp8;
- (void)setTitle:(id)fp8;
- (id)title;
- (id)okButton;
- (id)cancelButton;
- (void)dealloc;

@end

