/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSTableCell.h>

@class NSArray, NSDictionary, UIControl, UIProgressIndicator;

@interface PSControlTableCell : PSTableCell
{
    UIControl *_control;
    UIProgressIndicator *_progressIndicator;
    NSArray *_values;
    NSDictionary *_titleDict;
}

- (void)setValues:(id)fp8 titleDictionary:(id)fp12;
- (id)titleTextLabel;
- (id)valueTextLabel;
- (void)dealloc;
- (id)control;
- (BOOL)loading;
- (void)setLoading:(BOOL)fp8;
- (void)setControl:(id)fp8;
- (void)controlChanged:(id)fp8;
- (void)setValue:(id)fp8;

@end

