/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSViewController.h>

@class PSEditingPane, UIKeyboard, UIView;

@interface PSDetailController : PSViewController
{
    UIView *_view;
    PSEditingPane *_pane;
    UIKeyboard *_keyboard;
    BOOL _keyboardVisible;
}

- (void)_updateNavBarButtons;
- (id)initForContentSize:(struct CGSize)fp8;
- (void)dealloc;
- (void)viewWillRedisplay;
- (void)_addKeyboardView;
- (void)setPane:(id)fp8;
- (id)pane;
- (void)setKeyboardVisible:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)keyboardVisible;
- (void)viewWillBecomeVisible:(void *)fp8;
- (id)navigationTitle;
- (void)saveChanges;
- (void)suspend;
- (void)doneButtonClicked:(id)fp8;
- (void)cancelButtonClicked:(id)fp8;
- (void)navigationBarButtonClicked:(int)fp8;
- (void)popController;
- (id)view;

@end

