/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSListController.h>

@interface PSEditableListController : PSListController
{
    BOOL _editable;
}

- (id)initForContentSize:(struct CGSize)fp8;
- (void)_updateNavigationBar:(BOOL)fp8;
- (void)viewWillBecomeVisible:(void *)fp8;
- (void)viewWillRedisplay;
- (void)pushController:(id)fp8;
- (void)navigationBarButtonClicked:(int)fp8;
- (BOOL)editable;
- (void)setEditable:(BOOL)fp8;
- (BOOL)table:(id)fp8 canSelectRow:(int)fp12;
- (BOOL)table:(id)fp8 canDeleteRow:(int)fp12;
- (BOOL)performDeletionActionForSpecifier:(id)fp8;
- (void)table:(id)fp8 deleteRow:(int)fp12;

@end

