/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSTableCell.h>

@class UIImageView;

@interface PSImageCell : PSTableCell
{
    UIImageView *_imageView;
}

- (void)setImageView:(id)fp8;
- (void)drawTitleInRect:(struct CGRect)fp8 selected:(BOOL)fp24;

@end

