/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSListController.h>

@class PSSpecifier;

@interface PSListItemsController : PSListController
{
    int _rowToSelect;
    BOOL _deferItemSelection;
    PSSpecifier *_lastSelectedSpecifier;
}

- (void)viewWillRedisplay;
- (void)viewWillBecomeVisible:(void *)fp8;
- (void)scrollToSelectedCell;
- (void)setRowToSelect;
- (void)setValueForSpecifier:(id)fp8 defaultValue:(id)fp12;
- (void)dealloc;
- (void)suspend;
- (void)setSpecifiers:(id)fp8;
- (BOOL)preferencesTable:(id)fp8 isRow:(int)fp12 checkedInRadioGroup:(int)fp16;
- (BOOL)preferencesTable:(id)fp8 isRadioGroup:(int)fp12;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;
- (void)listItemSelected:(id)fp8;
- (void)tableSelectionDidChange:(id)fp8;
- (void)_addStaticText:(id)fp8;
- (id)itemsFromParent;
- (id)itemsFromDataSource;
- (id)specifiers;

@end

