/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSEditingPane.h>

@class UISegmentedControl;

@interface PSMultiValueEditingPane : PSEditingPane
{
    UISegmentedControl *_segmentedControl;
}

- (BOOL)requiresKeyboard;
- (BOOL)drawLabel;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setPreferenceSpecifier:(id)fp8;
- (int)selectedIndex;
- (void)selectIndex:(int)fp8;
- (void)setPreferenceValue:(id)fp8;
- (id)preferenceValue;
- (void)segmentedControl:(id)fp8 selectedSegmentChanged:(int)fp12;

@end

