/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

#import "PSBaseView-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, UINavigationBar, UIView;

@interface PSRootController : NSObject <PSBaseView>
{
    UIView *_contentView;
    UINavigationBar *_navBar;
    NSMutableArray *_controllers;
    NSString *_title;
    NSString *_idStr;
    struct CGSize _size;
    NSString *_navBarRightButtonTitle;
    int _navBarRightButtonStyle;
    BOOL _navBarRightButtonDirty;
    NSMutableSet *_tasks;
    BOOL _deallocating;
    unsigned char _hasTelephony;
}

+ (void)writePreference:(id)fp8;
+ (void)setPreferenceValue:(id)fp8 specifier:(id)fp12;
+ (id)readPreferenceValue:(id)fp8;
+ (BOOL)isOverlay;
- (void)setPreferenceValue:(id)fp8 specifier:(id)fp12;
- (id)readPreferenceValue:(id)fp8;
- (id)lastController;
- (id)initWithTitle:(id)fp8 identifier:(id)fp12;
- (void)updateNavButtons;
- (void)setupRootListForSize:(struct CGSize)fp8;
- (void)addTask:(id)fp8;
- (void)taskFinished:(id)fp8;
- (BOOL)busy;
- (id)contentView;
- (id)contentViewForTopController;
- (id)controllers;
- (id)specifiers;
- (BOOL)navigationBar:(id)fp8 shouldPopItem:(id)fp12;
- (id)initForContentSize:(struct CGSize)fp8;
- (void)setParentController:(id)fp8;
- (id)view;
- (id)navigationTitle;
- (id)navigationItem;
- (void)viewWillBecomeVisible:(void *)fp8;
- (void)viewWillRedisplay;
- (void)pushController:(id)fp8;
- (void)handleURL:(id)fp8;
- (BOOL)popControllerWithAnimation:(BOOL)fp8;
- (BOOL)popController;
- (void)pushNavigationItemWithTitle:(id)fp8;
- (void)pushNavigationItem:(id)fp8;
- (void)insertNavigationItem:(id)fp8 atIndexFromEnd:(int)fp12;
- (void)insertNavigationItem:(id)fp8 atIndex:(int)fp12;
- (void)navigationBar:(id)fp8 pushedItem:(id)fp12;
- (void)navigationBar:(id)fp8 poppedItem:(id)fp12;
- (void)popNavigationItem;
- (void)popNavigationItemWithAnimation:(BOOL)fp8;
- (void)hideNavigationBarButtons;
- (void)showLeftButton:(id)fp8 withStyle:(int)fp12 rightButton:(id)fp16 withStyle:(int)fp20;
- (void)showNavigationBarButtons:(id)fp8:(id)fp12;
- (void)setNavigationBarEnabled:(BOOL)fp8;
- (void)setPrompt:(id)fp8;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (void)navigationBarButtonClicked:(int)fp8;
- (void)suspend;
- (void)didLock;
- (void)willUnlock;
- (void)didUnlock;
- (void)didWake;
- (BOOL)deallocating;
- (BOOL)hasTelephony;
- (void)dealloc;
- (id)parentController;
- (void)lazyLoadBundle:(id)fp8;
- (id)navigationBar;
- (void)setRootController:(id)fp8;
- (id)rootController;
- (void)_pushController:(id)fp8;
- (void)_insertController:(id)fp8 atIndex:(int)fp12;
- (void)_popController;
- (void)_removeController:(id)fp8;
- (void)viewDidBecomeVisible;
- (void)viewTransitionCompleted;

@end

