/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSRootController.h>

@class NSDictionary;

@interface PSSetupController : PSRootController
{
    NSDictionary *_rootInfo;
    id <PSBaseView> _parentController;
}

+ (BOOL)isOverlay;
- (void)setupRootListForSize:(struct CGSize)fp8;
- (id)initForContentSize:(struct CGSize)fp8;
- (void)dealloc;
- (id)view;
- (id)parentController;
- (void)viewWillBecomeVisible:(void *)fp8;
- (void)didFinishTransition;
- (void)pushController:(id)fp8;
- (void)setParentController:(id)fp8;
- (id)controller;
- (void)dismiss;
- (void)pushControllerOnParentWithSpecifier:(id)fp8;
- (void)popControllerOnParent;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (void)updateNavButtons;
- (void)showNavigationBarButtons:(id)fp8:(id)fp12;
- (void)setPrompt:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (void)forwardInvocation:(id)fp8;

@end

