/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface PSSpecifier : NSObject
{
    id target;
    SEL getter;
    SEL setter;
    SEL action;
    Class detailControllerClass;
    int cellType;
    Class editPaneClass;
    int keyboardType;
    int autoCapsType;
    int autoCorrectionType;
    int textFieldType;
    NSString *_name;
    NSArray *_values;
    NSDictionary *_titleDict;
    NSDictionary *_shortTitleDict;
    id _userInfo;
    NSMutableDictionary *_properties;
}

+ (id)preferenceSpecifierNamed:(id)fp8 target:(id)fp12 set:(SEL)fp16 get:(SEL)fp20 detail:(Class)fp24 cell:(int)fp28 edit:(Class)fp32;
+ (id)groupSpecifierWithName:(id)fp8;
+ (id)emptyGroupSpecifier;
+ (int)autoCapsTypeForString:(id)fp8;
+ (int)keyboardTypeForString:(id)fp8;
- (id)init;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (void)removePropertyForKey:(id)fp8;
- (void)setProperties:(id)fp8;
- (id)properties;
- (void)loadValuesAndTitlesFromDataSource;
- (void)setValues:(id)fp8 titles:(id)fp12;
- (void)setValues:(id)fp8 titles:(id)fp12 shortTitles:(id)fp16;
- (void)setupIconImageWithPath:(id)fp8;
- (void)dealloc;
- (id)description;
- (id)name;
- (id)userInfo;
- (id)titleDictionary;
- (id)shortTitleDictionary;
- (id)identifier;
- (id)values;
- (void)setName:(id)fp8;
- (void)setUserInfo:(id)fp8;
- (void)setTitleDictionary:(id)fp8;
- (void)setShortTitleDictionary:(id)fp8;
- (void)setValues:(id)fp8;
- (void)setTarget:(id)fp8;
- (void)setKeyboardType:(int)fp8 autoCaps:(int)fp12 autoCorrection:(int)fp16;

@end

