/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface PSSystemConfiguration : NSObject
{
    struct __SCPreferences *_prefs;
}

+ (id)sharedInstance;
+ (void)releaseSharedInstance;
- (id)init;
- (void)dealloc;
- (unsigned char)lockAndSynchronize;
- (struct __CFString *)dataServiceID;
- (struct __CFString *)voicemailServiceID;
- (id)interfaceConfigurationValueForKey:(struct __CFString *)fp8 serviceID:(struct __CFString *)fp12;
- (void)setInterfaceConfigurationValue:(id)fp8 forKey:(struct __CFString *)fp12 serviceID:(struct __CFString *)fp16;
- (id)protocolConfiguration:(struct __CFString *)fp8 serviceID:(struct __CFString *)fp12;
- (void)setProtocolConfiguration:(id)fp8 protocolType:(struct __CFString *)fp12 serviceID:(struct __CFString *)fp16;
- (id)protocolConfigurationValueForKey:(struct __CFString *)fp8 protocolType:(struct __CFString *)fp12 serviceID:(struct __CFString *)fp16;
- (void)setProtocolConfigurationValue:(id)fp8 forKey:(struct __CFString *)fp12 protocolType:(struct __CFString *)fp16 serviceID:(struct __CFString *)fp20;

@end

