/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Preferences/PSEditingPane.h>

@class UITextField;

@interface PSTextEditingPane : PSEditingPane
{
    UITextField *_textField;
}

+ (struct CGSize)defaultSize;
- (BOOL)drawLabel;
- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)becomeFirstResponder;
- (void)setPreferenceValue:(id)fp8;
- (id)preferenceValue;
- (void)setPreferenceSpecifier:(id)fp8;

@end

