/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITextViewLegacy.h"

@class PSTextViewTableCell;

@interface PSTextView : UITextViewLegacy
{
    PSTextViewTableCell *_cell;
}

- (void)setCell:(id)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)scrollToMakeCaretVisible:(BOOL)fp8;
- (BOOL)resignFirstResponder;

@end

